# Generated by Django 2.1.15 on 2020-02-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_respuestas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestas',
            old_name='respuesta_text',
            new_name='respuesta',
        ),
    ]
